[package]
name = "rust-cxx-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = { version = "1.0.160", features = ["c++14", "c++17", "c++20"] }

[build-dependencies]
cc = "1.2.27"
cxx-build = { version = "1.0.160", features = ["parallel"] }
